### ISSUE TITLE
add requeriments.txt

### ISSUE THREAD

**Issue by DennisNgrox** [luizgmelo/Projeto-IP#3]
Se possível, sobe esse programa em um ambiente virtual:

python3 -m venv program_pizzaria

adiciona os arquivos nessa pasta e depois realiza as instalações das libs necessárias.

Logo depois executa na linha de comando: python3 pip freeze > requirements.txt

Adiciona aqui o github esse requirements.txt

Qualquer um que for utilizar seu código poderá executar: python3  -m pip install -r requirements.txt
E assim instalar todas as libs necessárias e até mesmo a versão do python utilizado!

valeu!

**Comment by luizgmelo** [comment]
O projeto não precisa baixar libs, porque são as que já vem integradas com python. Então só precisa ter o interpretador do python na máquina. Muito obrigado pela Issue.Utilizei o python 3.11.4 no projeto.
